In [1]:
# Seperate requests for different supermarkets split into

In [2]:
# Imports
import gmaps
import numpy as np
import pandas as pd
import requests
import time
from apikey import api_key
from pprint import pprint
import matplotlib as plt

# Loblaws

In [3]:
# Search Parameters for Loblaws Center + Request Page 1 
target_coordinates = "43.739541, -79.356733"
target_search = ("Loblaws")
target_radius = 13000
target_type = ("Supermarket")

params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": api_key
    }

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
response=requests.get(base_url, params=params)

In [4]:
result_list=[]
flag = True
count=0
while flag:
    count+=1
    print("Working on Page ",count)


    loblaws_data = response.json()
    lat_loblaws = []
    lng_loblaws = []
    results = loblaws_data['results']
    loblaws_geo = pd.DataFrame(results)['geometry']
    loblaws_title = pd.DataFrame(results)['name']
    for x in loblaws_geo:
        loblaws_location = pd.DataFrame(x)['location']
        lat_loblaws.append(loblaws_location['lat'])
        lng_loblaws.append(loblaws_location['lng'])
    

    loblaws_lat_pd = pd.DataFrame(lat_loblaws)
    loblaws_lng_pd = pd.DataFrame(lng_loblaws)
    loblaws_title_pd = pd.DataFrame(loblaws_title)
    loblaws_title_pd.join(loblaws_lat_pd)
    loblaws_title_pd['C'] = loblaws_title_pd.reset_index().index
    loblaws_lat_pd['C'] = loblaws_lat_pd.reset_index().index
    loblaws_lng_pd['C'] = loblaws_lng_pd.reset_index().index
    sample2=pd.merge(loblaws_title_pd,loblaws_lat_pd,on='C')
    sample1=pd.merge(sample2,loblaws_lng_pd,on='C')
    result_list.append(sample1)

    if('next_page_token' in loblaws_data):
        paramaters = {
        "key": api_key,
        "pagetoken":loblaws_data['next_page_token']
        }
        time.sleep(2)

        response=requests.get(base_url, paramaters)
    else:
        flag=False

Working on Page  1
Working on Page  2
Working on Page  3

In [5]:
result_df = pd.concat(result_list, ignore_index=True)[['name','0_x','0_y']]

loblaws_locations_pd = pd.DataFrame(result_df)
loblaws_locations_pd.iloc[0:19]

       name        0_x        0_y
0   Loblaws  43.707189 -79.394402
1   Loblaws  43.696551 -79.370546
2   Loblaws  43.688420 -79.393510
3   Loblaws  43.699149 -79.359698
4   Loblaws  43.683889 -79.415833
5   Loblaws  43.735524 -79.404497
6   Loblaws  43.672095 -79.420975
7   Loblaws  43.675117 -79.358417
8   Loblaws  43.661964 -79.379600
9   Loblaws  43.644486 -79.369677
10  Loblaws  43.768842 -79.412239
11  Loblaws  43.688105 -79.288514
12  Loblaws  43.768751 -79.387240
13  Loblaws  43.665576 -79.495369
14  Loblaws  43.660996 -79.328281
15  Loblaws  43.655138 -79.449275
16  Loblaws  43.843196 -79.410774
17  Loblaws  43.661513 -79.519770
18  Loblaws  43.647082 -79.401825

# Longos

In [6]:
# Search Parameters for Longos Center + Request Page 1 
target_coordinates = "43.739541, -79.356733"
target_search = ("Longos")
target_radius = 13000
target_type = ("Supermarket")

params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": api_key
    }

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
response=requests.get(base_url, params=params)

In [7]:
result_list=[]
flag = True
count=0
while flag:
    count+=1
    print("Working on Page ",count)


    longos_data = response.json()
    lat_longos = []
    lng_longos = []
    results = longos_data['results']
    longos_geo = pd.DataFrame(results)['geometry']
    longos_title = pd.DataFrame(results)['name']
    for x in longos_geo:
        longos_location = pd.DataFrame(x)['location']
        lat_longos.append(longos_location['lat'])
        lng_longos.append(longos_location['lng'])
    

    longos_lat_pd = pd.DataFrame(lat_longos)
    longos_lng_pd = pd.DataFrame(lng_longos)
    longos_title_pd = pd.DataFrame(longos_title)
    longos_title_pd.join(longos_lat_pd)
    longos_title_pd['C'] = longos_title_pd.reset_index().index
    longos_lat_pd['C'] = longos_lat_pd.reset_index().index
    longos_lng_pd['C'] = longos_lng_pd.reset_index().index
    sample2=pd.merge(longos_title_pd,longos_lat_pd,on='C')
    sample1=pd.merge(sample2,longos_lng_pd,on='C')
    result_list.append(sample1)

    if('next_page_token' in longos_data):
        paramaters = {
        "key": api_key,
        "pagetoken":longos_data['next_page_token']
        }
        time.sleep(2)

        response=requests.get(base_url, paramaters)
    else:
        flag=False

Working on Page  1

In [8]:
result_df = pd.concat(result_list, ignore_index=True)[['name','0_x','0_y']]

longos_locations_pd = pd.DataFrame(result_df)
longos_locations_pd

                                             name        0_x        0_y
0                        Longo's Yonge & Sheppard  43.762509 -79.410532
1                              Longo's York Mills  43.754474 -79.356895
2                                 Longo's Bayview  43.813776 -79.399004
3                                 Longo's Leaside  43.706454 -79.359523
4                                 Longo's Markham  43.849503 -79.355126
5                                Longo's Bathurst  43.847738 -79.461390
6                           The Market by Longo's  43.655376 -79.384863
7                           The Market by Longo's  43.686667 -79.399722
8                       Longo's Maple Leaf Square  43.642452 -79.380917
9                           The Market by Longo's  43.670946 -79.384457
10      The Market by Longo's at Brookfield Place  43.647277 -79.378699
11  The Market by Longo's at First Canadian Place  43.648387 -79.382254
12                        Longo's Liberty Village  43.639985 -79.423193
13                            Longo's Pronto Eats  43.671098 -79.386063

# Metro

In [9]:
# Search Parameters for Longos Center + Request Page 1 
target_coordinates = "43.739541, -79.356733"
target_search = ("Metro")
target_radius = 13000
target_type = ("Supermarket")

params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": api_key
    }

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
response=requests.get(base_url, params=params)

In [10]:
result_list=[]
flag = True
count=0
while flag:
    count+=1
    print("Working on Page ",count)


    metro_data = response.json()
    lat_metro = []
    lng_metro = []
    results = metro_data['results']
    metro_geo = pd.DataFrame(results)['geometry']
    metro_title = pd.DataFrame(results)['name']
    for x in metro_geo:
        metro_location = pd.DataFrame(x)['location']
        lat_metro.append(metro_location['lat'])
        lng_metro.append(metro_location['lng'])
    

    metro_lat_pd = pd.DataFrame(lat_metro)
    metro_lng_pd = pd.DataFrame(lng_metro)
    metro_title_pd = pd.DataFrame(metro_title)
    metro_title_pd.join(metro_lat_pd)
    metro_title_pd['C'] = metro_title_pd.reset_index().index
    metro_lat_pd['C'] = metro_lat_pd.reset_index().index
    metro_lng_pd['C'] = metro_lng_pd.reset_index().index
    sample2=pd.merge(metro_title_pd,metro_lat_pd,on='C')
    sample1=pd.merge(sample2,metro_lng_pd,on='C')
    result_list.append(sample1)

    if('next_page_token' in metro_data):
        paramaters = {
        "key": api_key,
        "pagetoken":metro_data['next_page_token']
        }
        time.sleep(2)

        response=requests.get(base_url, paramaters)
    else:
        flag=False

Working on Page  1
Working on Page  2
Working on Page  3

In [11]:
result_df = pd.concat(result_list, ignore_index=True)[['name','0_x','0_y']]

metro_locations_pd = pd.DataFrame(result_df)
metro_locations_pd.iloc[0:37]

                        name        0_x        0_y
0                      Metro  43.774373 -79.413118
1                      Metro  43.756122 -79.440061
2                      Metro  43.747215 -79.385524
3                      Metro  43.726826 -79.403105
4                      Metro  43.733890 -79.343711
5                      Metro  43.728217 -79.481295
6                      Metro  43.719624 -79.430884
7                      Metro  43.707102 -79.399536
8                      Metro  43.797763 -79.318416
9                      Metro  43.710985 -79.378265
10                     Metro  43.708335 -79.476884
11                     Metro  43.756443 -79.313690
12                     Metro  43.666281 -79.405124
13                     Metro  43.654183 -79.419414
14                     Metro  43.770898 -79.281952
15                     Metro  43.724217 -79.298282
16                     Metro  43.689722 -79.288623
17                     Metro  43.648955 -79.373178
18            Metro Pharmacy  43.774369 -79.412782
19                     Metro  43.658246 -79.377061
20                     Metro  43.742981 -79.216804
21                     Metro  43.639724 -79.417598
22                     Metro  43.669641 -79.473025
23                     Metro  43.623158 -79.482642
24  Metro at West Queen West  43.642617 -79.427870
25            Metro Pharmacy  43.766733 -79.388931
26            Metro Pharmacy  43.689892 -79.288684
27                     Metro  43.791348 -79.444642
28       Metro grocery store  43.755640 -79.440557
29                     Metro  43.660793 -79.383795
30            Metro Pharmacy  43.756650 -79.313506
31            Metro Pharmacy  43.742522 -79.216613
32            Metro Pharmacy  43.669784 -79.473686
33            Metro Pharmacy  43.648932 -79.373158
34            Metro Pharmacy  43.639918 -79.417875
35            Metro Pharmacy  43.770792 -79.282173
36             Finch Station  43.780152 -79.415471

# Walmart

In [12]:
# Search Parameters for Longos Center + Request Page 1 
target_coordinates = "43.739541, -79.356733"
target_search = ("Walmart")
target_radius = 13000
target_type = ("Supermarket")

params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": api_key
    }

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
response=requests.get(base_url, params=params)

In [13]:
result_list=[]
flag = True
count=0
while flag:
    count+=1
    print("Working on Page ",count)


    walmart_data = response.json()
    lat_walmart = []
    lng_walmart = []
    results = walmart_data['results']
    walmart_geo = pd.DataFrame(results)['geometry']
    walmart_title = pd.DataFrame(results)['name']
    for x in walmart_geo:
        walmart_location = pd.DataFrame(x)['location']
        lat_walmart.append(walmart_location['lat'])
        lng_walmart.append(walmart_location['lng'])
    

    walmart_lat_pd = pd.DataFrame(lat_walmart)
    walmart_lng_pd = pd.DataFrame(lng_walmart)
    walmart_title_pd = pd.DataFrame(walmart_title)
    walmart_title_pd.join(walmart_lat_pd)
    walmart_title_pd['C'] = walmart_title_pd.reset_index().index
    walmart_lat_pd['C'] = walmart_lat_pd.reset_index().index
    walmart_lng_pd['C'] = walmart_lng_pd.reset_index().index
    sample2=pd.merge(walmart_title_pd,walmart_lat_pd,on='C')
    sample1=pd.merge(sample2,walmart_lng_pd,on='C')
    result_list.append(sample1)

    if('next_page_token' in walmart_data):
        paramaters = {
        "key": api_key,
        "pagetoken":walmart_data['next_page_token']
        }
        time.sleep(2)

        response=requests.get(base_url, paramaters)
    else:
        flag=False

Working on Page  1
Working on Page  2

In [14]:
result_df = pd.concat(result_list, ignore_index=True)[['name','0_x','0_y']]

walmart_locations_pd = pd.DataFrame(result_df)
walmart_locations_pd

                                                 name        0_x        0_y
0               Walmart Toronto Downsview Supercentre  43.757716 -79.488970
1                       Walmart Thornhill Supercentre  43.811635 -79.451138
2                    Walmart Toronto North York Store  43.708581 -79.473372
3                     Walmart Toronto Agincourt Store  43.784543 -79.291226
4                Walmart Scarborough West Supercentre  43.728392 -79.295652
5             Walmart Richmond Hill South Supercentre  43.842042 -79.416012
6              Walmart Gerrard Square (Toronto) Store  43.668656 -79.338721
7                                             Walmart  43.656304 -79.435504
8                                 Walmart Supercentre  43.668000 -79.484749
9                                    Walmart Pharmacy  43.811568 -79.451178
10              Walmart Toronto (Sheridan Mall) Store  43.722303 -79.511031
11              Walmart Scarborough Town Centre Store  43.777151 -79.258635
12         Walmart Scarborough North East Supercentre  43.833779 -79.255731
13              Walmart Scarborough South Supercentre  43.742800 -79.223791
14                             Walmart Grocery Pickup  43.656409 -79.435541
15                           Vision Center At Walmart  43.784505 -79.291303
16                                   Walmart Pharmacy  43.742588 -79.223080
17                             Walmart Grocery Pickup  43.797790 -79.200879
18  Walmart Grocery Pickup & Delivery - PenguinPickUp  43.645164 -79.402457
19                                   Walmart Pharmacy  43.708779 -79.473904
20                                   Walmart Pharmacy  43.722108 -79.511575
21  Walmart Grocery Pickup & Delivery - PenguinPickUp  43.642313 -79.424366
22  Walmart Grocery Pickup & Delivery - PenguinPickUp  43.663583 -79.367474
23                             Walmart Grocery Pickup  43.842067 -79.415880
24                                   Walmart Pharmacy  43.784535 -79.291145
25        Walmart Morningside Scarborough Supercentre  43.797836 -79.200825
26                                   Walmart Pharmacy  43.656326 -79.435420
27                                   Walmart Pharmacy  43.777146 -79.258243
28                                   Walmart Pharmacy  43.833261 -79.255194
29                                   Walmart Pharmacy  43.757883 -79.488492
30                                   Walmart Pharmacy  43.668642 -79.338745
31                                   Walmart Pharmacy  43.842067 -79.416093
32                              Walmart Vision Centre  43.708317 -79.474062
33                              Walmart Vision Center  43.728341 -79.295820
34                           Vision Center At Walmart  43.811642 -79.451165
35                                      Vision Center  43.656413 -79.435873
36                             Walmart Grocery Pickup  43.668393 -79.485000

In [15]:
json_walmart = walmart_locations_pd.tojson()
json_walmart

AttributeError: 'DataFrame' object has no attribute 'tojson'